name = "devnoder-collab"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "CollabRoom"
class_name = "CollabRoom"
script_name = "devnoder-collab"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CollabRoom"]

[[d1_databases]]
binding = "DB"
database_name = "devnoder-db"
database_id = "e5aaf35e-b8e7-4dc3-ad29-aa1dfaa6852e"
